name: GitHub Actions Demo
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Grant gradle permission
        run: chmod +x ./gradlew
      - name: Run test
        run: ./gradlew test